### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by TinyKitten** [mak0tia/Matsuya-Web-API#15]
# GraphQL対応

* いかんのか？
* 乗るしか無いこのビッグウェーブ

**Comment by mak0tia** [comment]
別でブランチ切って開発するのと別リポジトリで開発するのどっちがいいん
ていうか今の状態だとall.jsonのデータ返すだけだからめちゃくちゃ楽でいいんだけど今後の拡張考えると(Issue #1 )どうなんだろ

**Comment by TinyKitten** [comment]
ブランチでいいと思うゾ
GraphQLだったら
```
{
  menu(name: "gyumeshi") {
    nutrition
  }
}
```
な感じだと思うゾ

**Comment by mak0tia** [comment]
all.jsonの中身もいろいろアレなので(栄養価情報も入れた情報に)書き直そうと思ってたけどこれだとどうなるの

**Comment by TinyKitten** [comment]
普通に書き足せばええんちゃう

**Comment by mak0tia** [comment]
少し色々調べたらやってみるわ
