### ISSUE TITLE
アイコン作る

### ISSUE THREAD

**Issue by mak0tia** [mak0tia/Matsuya-Web-API#44]
# 内容

* アイコンないと自分のサイトに載せるときうーんって感じだしあれ

**Comment by TinyKitten** [comment]
![full](https://user-images.githubusercontent.com/32848922/35209222-f1f4d106-ff8f-11e7-91e0-9e51c7ee0536.png)
![icon](https://user-images.githubusercontent.com/32848922/35209224-f38414f0-ff8f-11e7-81f6-b1d20af8269e.png)
クソロゴ作った

**Comment by mak0tia** [comment]
@TinyKitten これのサイズクソでかいバージョン送ってくれることを期待してる

**Comment by TinyKitten** [comment]
どれくらい？

**Comment by mak0tia** [comment]
2000×2000くらいあれば十分っしょ()

**Comment by TinyKitten** [comment]
![full](https://user-images.githubusercontent.com/32848922/35213732-f944091a-ffa1-11e7-956c-78f3fdc9701d.png)
![icon](https://user-images.githubusercontent.com/32848922/35213734-fb66ec9e-ffa1-11e7-8aa0-5771dd362505.png)
ここで貼って2000x2000になるのかな

**Comment by mak0tia** [comment]
なったみたい
ありがと 🍆
