### ISSUE TITLE
【新コーナー】ｱｼｸｱｳｪｯｳｪ

### ISSUE THREAD

**Issue by TinyKitten** [mak0tia/Matsuya-Web-API#61]
# 内容

* async/awaitで書き直してみたらなんかスマートにかけたのでご報告致します
<img width="1109" alt="2018-02-26 9 36 01" src="https://user-images.githubusercontent.com/32848922/36648566-7879c6a6-1ad8-11e8-8323-3a6e3a048f11.png">
<img width="283" alt="2018-02-26 9 44 46" src="https://user-images.githubusercontent.com/32848922/36648667-b4e741bc-1ad9-11e8-8849-bbb41b7dde64.png">
エラー処理はうんち以下なのでアレ

**Comment by mak0tia** [comment]
`import dbcontroller from "../modules/dbcontroller.js"` じゃないですかねぇ(クソリプ)

**Comment by TinyKitten** [comment]
ディレクトリよく見て

**Comment by mak0tia** [comment]
なんでそこにあるんですかねぇ(´･_･`)
