### ISSUE TITLE
moanの現在分詞。(苦痛・悲しみの)うめき(声)

### ISSUE THREAD

**Issue by TinyKitten** [mak0tia/Matsuya-Web-API#64]
# データの一部が誤字っている

* 誤字は誤字であると見抜ける人でないと(MWAを使うのは)難しい

<img width="216" alt="2018-06-28 16 47 07" src="https://user-images.githubusercontent.com/32848922/42020588-3b72491a-7af3-11e8-9956-d7eafaac265c.png">
<img width="668" alt="2018-06-28 16 47 15" src="https://user-images.githubusercontent.com/32848922/42020589-3b946e5a-7af3-11e8-9873-388246103f10.png">

**Comment by mak0tia** [comment]
@TinyKitten 価格改定のあと、データの差し替えもできていなかったのでそちらと同時に処理します
