### ISSUE TITLE
鼻くそを炒めて食べると死ぬほどうまいぞ

### ISSUE THREAD

**Issue by TinyKitten** [mak0tia/Matsuya-Web-API#7]
# 簡易的なテストを書いてCIを導入する

* 機能追加後のバグに柔軟に対応できる
* なんとリリース用ブランチにpushさてテストに成功すると自動的にHeorkuにぶっ込まれる
* チキンラーメンぶっ込み飯食ったけどただの雑炊だった

**Comment by mak0tia** [comment]
タイトルと最後の文は理解できないけどCIってどのサービス使えばいいのかわからなくてアレ
なんかいいのありますか

**Comment by TinyKitten** [comment]
書くの忘れてた()
俺はTravis CI使ってるゾ

**Comment by mak0tia** [comment]
#9 と #11 多分これまとめていいと思うんだけどどうやって書くのかわからんしPR飛ばして()
