### ISSUE TITLE
エラーメッセージがHTML

### ISSUE THREAD

**Issue by TinyKitten** [mak0tia/Matsuya-Web-API#8]
# 例えば存在しないパスを参照するとHTMLでエラーが返される（４０４）

* 別に必要ないとは思うけどHTMLで返すのは個人的にアレルギー
*  吾妻郡のアガツマっていい感じに扱われてるけど結局アレって自殺した妻を「我妻よ・・・」って悔やんだクソみたいな話だよね。

**Comment by mak0tia** [comment]
逆になにで返せばいいの()

**Comment by Kadoshita** [comment]
@mak0tia プルリク書いてみた
